### ISSUE TITLE
Very Interesting

### ISSUE THREAD

**Issue by ghost** [Jerenaux/phaserquest#6]
I've been working with BrowserQuest for a couple years now, and this is something new indeed. I am loving it thus far, though it seems a bit choppy around the edges. Anyway, what is the compatibility with mobile devices? Does this take away from that of the original BQ?

Regardless, I am re-writing BQ from absolute scratch (still maintaining some aspects) and still using the canvas system, and thus far I have improved the rendering tremendously. I encourage you to take a look at my repository :)

https://github.com/Tach-Yon/Kaetram

**Comment by Jerenaux** [comment]
I admit that I have totally neglected mobile compatibility! I thought I could leave it under the very end, and then I noticed I should have been thinking about it from the beginning. I haven't found time since to really tackle this. So yes, this is a big flaw of PQ with respect to BQ!

I had a look at your project, it seems really nice! I haven't' been able to properly play it (I'll create an issue), but the presentation and the code are really promising! I'll be following that (and I can feature it on my website if you'd like). 

Is there a particular reason why you wanted to make it from scratch, instead of using an existing game engine, aside from the learning experience?

**Comment by ghost** [comment]
My other game (which is based off BQ) has been in development for nearly two years, with various developers contributing. So you can imagine the code has become so cluttered and convoluted, and plain out inefficient. Plus, because everything was horribly programmed, I would spent too much time trying to piece everything together at times.

It is not ready yet, I should have it done within a week or so :)

**Comment by Jerenaux** [comment]
Cool, I'll be looking forward to it! In the meantime I've added a link to your Kaetram repository on Phaser Quest's page, as people interested in PQ would surely be interested in Kaetram!

**Comment by Veradictus** [comment]
Hey Jerenaux, I wanted to let you know of my latest version of Kaetram. It has come a long way, so please check it out when you can (the development version on GitHub even has some WebGL support) https://github.com/Veradictus/Kaetram-Open
